### ISSUE TITLE
Follow Up Docs Updates

### ISSUE THREAD

**Issue by demariadaniel** [Pan-Canadian-Genome-Library/daco#14]
A) Revise project summary based off existing project resources
https://oicr.slack.com/archives/C066W5703RU/p1729525647009309

B) Review OHCRN docs for Readme updates:
https://github.com/Pan-Canadian-Genome-Library/daco/pull/7#discussion_r1797349729

C) Remove (or update) Overture template docs accordingly:
https://github.com/Pan-Canadian-Genome-Library/daco/pull/7#pullrequestreview-2386149183

**Comment by Buwujiu** [comment]
@demariadaniel You can use the following as project summary: Canada boasts world-leading expertise in genomics, including developing data-sharing policies and tools. However, we lack a national strategy to aggregate, store and share Canadian data equitably, securely and sustainably. At the same time, the size and complexity of human genomics datasets and their associated clinical data are growing rapidly. The Pan-Canadian Genome Library (PCGL) is a large collaborative effort to unify Canada's genome sequencing efforts. The PCGL is an open-source and open-science initiative, building upon Canadian-made foundational components and datasets, and utilizing international standards such as GA4GH to unify Canada’s human genome sequencing efforts.

**Comment by Buwujiu** [comment]
PR merged, closing.
