### ISSUE TITLE
Design Mobile-Friendly Homepage

### ISSUE THREAD

**Issue by Buwujiu** [Pan-Canadian-Genome-Library/daco#75]
Create homepage mockup for mobile and tablets. Only the homepage will be optimized for mobile. 
Will also include a message in the homepage to let users know that the rest of the pages are not optimized for mobile and tablets.

**Comment by patrickdsantos** [comment]
Mocks included in the PCGL Figma link:https://www.figma.com/design/L4TWNoqAOOV9d0IBVUibIp/PCGL%2FDesign%2FMockups?node-id=2706-11866&t=DjPpjZFjV9otMkwM-1

**Comment by patrickdsantos** [comment]
Hey @Buwujiu let me know what you think! ^^^

**Comment by Buwujiu** [comment]
@patrickdsantos mocks look great to me! Thanks Patrick!
